(Dialog KeyDialog
    (Components
        (SubLayout Content)
        (Separator CommitSeparator)
        (PushButton CommitOK)
        (PushButton CommitCancel)
    )
    (Resources
        (CommitSeparator.ResourceHints "Template:OKCancelDialog.CommitSeparator")
        (CommitOK.Label "OK")
        (CommitOK.TopOffset 10)
        (CommitOK.BottomOffset 10)
        (CommitOK.LeftOffset 40)
        (CommitOK.RightOffset 0)
        (CommitOK.ResourceHints "Template:OKCancelDialog.CommitOK")
        (CommitCancel.Label "Cancel")
        (CommitCancel.TopOffset 10)
        (CommitCancel.BottomOffset 10)
        (CommitCancel.LeftOffset 8)
        (CommitCancel.RightOffset 10)
        (CommitCancel.ResourceHints "Template:OKCancelDialog.CommitCancel")
        (.TopOffset 0)
        (.BottomOffset 0)
        (.LeftOffset 0)
        (.RightOffset 0)
        (.DefaultButton "CommitOK")
        (.ResourceHints "Template:OKCancelDialog" "Guidelines:Creo4-Dialog" "GuidelinesVersion:1" "Version:Creo4" "@Subgrid0x2.Template:OKCancelDialog.CommitBar")
        (.Accelerator "Esc")
        (.AttachLeft True)
        (.Label "Построение шпонки по ГОСТ 23360-78")
        (.Layout
            (Grid
                (Rows 1 0 0)
                (Cols 1)
                Content CommitSeparator
                (Grid
                    (Rows 1)
                    (Cols 1 0 0)
                    (Pos 1 2)
                    CommitOK
                    (Pos 1 3)
                    CommitCancel
                )
            )
        )
    )
)
(Layout Content
    (Components
        (Tab Tab1 Layout1 Layout2)
        (Label Label8)
        (Label Label5)
        (CheckButton CheckButton4)
        (Label Label7)
        (CheckButton CheckButton5)
        (Label Label6)
        (CheckButton CheckButton6)
        (Separator Separator1)
        (Label Label1)
        (InputPanel InputPanel1)
        (Separator Separator2)
        (Label Label3)
        (InputPanel InputPanel2)
        (PushButton PushButton1)
    )
    (Resources
        (Tab1.Decorated 1)
        (Tab1.Names "1" "3" "2")
        (Tab1.Labels "Test1" "Test2" "Test3")
        (Tab1.TopOffset 0)
        (Tab1.BottomOffset 2)
        (Tab1.LeftOffset 0)
        (Tab1.RightOffset 0)
        (Tab1.AlwaysOnTop True)
        (Label8.Label "Выберите исполнение:")
        (Label8.AttachLeft True)
        (Label8.TopOffset 1)
        (Label8.BottomOffset 0)
        (Label8.LeftOffset 0)
        (Label8.RightOffset 0)
        (Label5.Label "1")
        (Label5.AttachLeft True)
        (Label5.AttachRight True)
        (Label5.ResourceHints "UserOverrideAttrs:AttachRight")
        (Label5.Alignment 1)
        (Label5.TopOffset 0)
        (Label5.BottomOffset 7)
        (Label5.LeftOffset 0)
        (Label5.RightOffset 4)
        (CheckButton4.AttachLeft True)
        (CheckButton4.TopOffset 0)
        (CheckButton4.BottomOffset 7)
        (CheckButton4.LeftOffset 3)
        (CheckButton4.RightOffset 4)
        (Label7.Label "2")
        (Label7.AttachLeft True)
        (Label7.AttachRight True)
        (Label7.ResourceHints "UserOverrideAttrs:AttachRight")
        (Label7.Alignment 1)
        (Label7.TopOffset 0)
        (Label7.BottomOffset 7)
        (Label7.LeftOffset 3)
        (Label7.RightOffset 4)
        (CheckButton5.AttachLeft True)
        (CheckButton5.TopOffset 0)
        (CheckButton5.BottomOffset 7)
        (CheckButton5.LeftOffset 3)
        (CheckButton5.RightOffset 4)
        (Label6.Label "3")
        (Label6.AttachLeft True)
        (Label6.AttachRight True)
        (Label6.ResourceHints "UserOverrideAttrs:AttachRight")
        (Label6.Alignment 1)
        (Label6.TopOffset 0)
        (Label6.BottomOffset 7)
        (Label6.LeftOffset 3)
        (Label6.RightOffset 4)
        (CheckButton6.AttachLeft True)
        (CheckButton6.TopOffset 0)
        (CheckButton6.BottomOffset 7)
        (CheckButton6.LeftOffset 3)
        (CheckButton6.RightOffset 0)
        (Separator1.TopOffset 7)
        (Separator1.BottomOffset 7)
        (Label1.Label "Имя новой модели:")
        (Label1.AttachLeft True)
        (Label1.TopOffset 6)
        (Label1.BottomOffset 2)
        (Label1.LeftOffset 0)
        (Label1.RightOffset 0)
        (InputPanel1.Columns 8)
        (InputPanel1.TopOffset 1)
        (InputPanel1.BottomOffset 8)
        (InputPanel1.LeftOffset 0)
        (InputPanel1.RightOffset 0)
        (InputPanel1.InputType 0)
        (InputPanel1.CompleteMatch True)
        (Separator2.TopOffset 8)
        (Separator2.BottomOffset 8)
        (Label3.Label "Сохранить в папку:")
        (Label3.AttachLeft True)
        (Label3.TopOffset 8)
        (Label3.BottomOffset 0)
        (Label3.LeftOffset 0)
        (Label3.RightOffset 4)
        (InputPanel2.TopOffset 8)
        (InputPanel2.BottomOffset 0)
        (InputPanel2.LeftOffset 3)
        (InputPanel2.RightOffset 4)
        (PushButton1.Label "Выбрать")
        (PushButton1.AttachLeft True)
        (PushButton1.TopOffset 8)
        (PushButton1.BottomOffset 0)
        (PushButton1.LeftOffset 3)
        (PushButton1.RightOffset 0)
        (.AttachLeft True)
        (.AttachRight True)
        (.AttachTop True)
        (.TopOffset 16)
        (.BottomOffset 16)
        (.LeftOffset 10)
        (.RightOffset 10)
        (.ResourceHints "Template:OKCancelDialog.Content")
        (.AttachBottom True)
        (.Layout
            (Grid
                (Rows 1 0 0 0 0 0 0 0)
                (Cols 0 0 0 0 1 1)
                (Size 1 6)
                Tab1
                (Size 1 6)
                Label8 Label5 CheckButton4 Label7 CheckButton5 Label6 CheckButton6
                (Size 1 6)
                Separator1
                (Size 1 6)
                Label1
                (Size 1 6)
                InputPanel1
                (Size 1 6)
                Separator2 Label3
                (Size 1 4)
                InputPanel2 PushButton1
            )
        )
    )
)
(Layout Layout1
    (Components
        (Label Label2)
        (Label Label10)
        (OptionMenu OptionMenu1)
        (Label Label11)
        (OptionMenu OptionMenu2)
        (Label Label12)
        (OptionMenu OptionMenu3)
    )
    (Resources
        (Label2.Label "Выберите размеры:")
        (Label2.AttachLeft True)
        (Label2.TopOffset 10)
        (Label2.BottomOffset 2)
        (Label2.LeftOffset 10)
        (Label2.RightOffset 10)
        (Label10.Label "Длина")
        (Label10.AttachLeft True)
        (Label10.TopOffset 1)
        (Label10.BottomOffset 3)
        (Label10.LeftOffset 10)
        (Label10.RightOffset 4)
        (OptionMenu1.Names "0")
        (OptionMenu1.Labels "(not selected)")
        (OptionMenu1.TopOffset 1)
        (OptionMenu1.BottomOffset 3)
        (OptionMenu1.LeftOffset 3)
        (OptionMenu1.RightOffset 10)
        (OptionMenu1.Columns 10)
        (Label11.Label "Ширина")
        (Label11.AttachLeft True)
        (Label11.TopOffset 3)
        (Label11.BottomOffset 3)
        (Label11.LeftOffset 10)
        (Label11.RightOffset 4)
        (OptionMenu2.TopOffset 3)
        (OptionMenu2.BottomOffset 3)
        (OptionMenu2.LeftOffset 3)
        (OptionMenu2.RightOffset 10)
        (OptionMenu2.Columns 10)
        (OptionMenu2.Names "0")
        (OptionMenu2.Labels "(not selected)")
        (Label12.Label "Высота")
        (Label12.AttachLeft True)
        (Label12.TopOffset 3)
        (Label12.BottomOffset 13)
        (Label12.LeftOffset 10)
        (Label12.RightOffset 4)
        (OptionMenu3.TopOffset 3)
        (OptionMenu3.BottomOffset 13)
        (OptionMenu3.LeftOffset 3)
        (OptionMenu3.RightOffset 10)
        (OptionMenu3.Columns 10)
        (OptionMenu3.Names "0")
        (OptionMenu3.Labels "(not selected)")
        (.Label "Выбор размеров")
        (.Layout
            (Grid
                (Rows 0 0 0 0)
                (Cols 0 1)
                (Size 1 2)
                Label2 Label10 OptionMenu1 Label11 OptionMenu2 Label12 OptionMenu3
            )
        )
    )
)
(Layout Layout2
    (Components
        (Label Label4)
        (InputPanel InputPanel3)
        (Label Label13)
        (InputPanel InputPanel5)
        (Label Label14)
        (OptionMenu OptionMenu4)
        (Tab Tab2 Layout3 Layout4)
    )
    (Resources
        (Label4.Label "Диаметр вала (мм):")
        (Label4.AttachLeft True)
        (Label4.TopOffset 13)
        (Label4.BottomOffset 3)
        (Label4.LeftOffset 10)
        (Label4.RightOffset 4)
        (InputPanel3.TopOffset 13)
        (InputPanel3.BottomOffset 3)
        (InputPanel3.LeftOffset 3)
        (InputPanel3.RightOffset 10)
        (Label13.Label "Допускаемое напряжение (Н/мм2):")
        (Label13.AttachLeft True)
        (Label13.TopOffset 3)
        (Label13.BottomOffset 3)
        (Label13.LeftOffset 10)
        (Label13.RightOffset 4)
        (InputPanel5.TopOffset 3)
        (InputPanel5.BottomOffset 3)
        (InputPanel5.LeftOffset 3)
        (InputPanel5.RightOffset 10)
        (Label14.Label "Сечение: ")
        (Label14.AttachLeft True)
        (Label14.TopOffset 3)
        (Label14.BottomOffset 3)
        (Label14.LeftOffset 10)
        (Label14.RightOffset 4)
        (OptionMenu4.Sensitive False)
        (OptionMenu4.Names "0")
        (OptionMenu4.Labels "(not selected)")
        (OptionMenu4.TopOffset 3)
        (OptionMenu4.BottomOffset 3)
        (OptionMenu4.LeftOffset 3)
        (OptionMenu4.RightOffset 10)
        (Tab2.Decorated 1)
        (Tab2.TopOffset 3)
        (Tab2.BottomOffset 13)
        (Tab2.LeftOffset 10)
        (Tab2.RightOffset 10)
        (Tab2.AlwaysOnTop True)
        (.Label "Расчет по диаметру вала и моменту сил")
        (.Layout
            (Grid
                (Rows 0 0 0 1)
                (Cols 0 1)
                Label4 InputPanel3 Label13 InputPanel5 Label14 OptionMenu4
                (Size 1 2)
                Tab2
            )
        )
    )
)
(Layout Layout3
    (Components
        (Label Label9)
        (InputPanel InputPanel4)
    )
    (Resources
        (Label9.Label "Момент сил (Нм):")
        (Label9.AttachLeft True)
        (Label9.TopOffset 13)
        (Label9.BottomOffset 13)
        (Label9.LeftOffset 10)
        (Label9.RightOffset 4)
        (InputPanel4.TopOffset 13)
        (InputPanel4.BottomOffset 13)
        (InputPanel4.LeftOffset 3)
        (InputPanel4.RightOffset 10)
        (.Label "Момент сил известен")
        (.Layout
            (Grid
                (Rows 0)
                (Cols 0 1)
                Label9 InputPanel4
            )
        )
    )
)
(Layout Layout4
    (Components
        (Label Label16)
        (OptionMenu OptionMenu5)
    )
    (Resources
        (Label16.Label "Выберите длину:")
        (Label16.AttachLeft True)
        (Label16.TopOffset 13)
        (Label16.BottomOffset 13)
        (Label16.LeftOffset 10)
        (Label16.RightOffset 4)
        (OptionMenu5.Sensitive False)
        (OptionMenu5.Names "0")
        (OptionMenu5.Labels "(not selected)")
        (OptionMenu5.TopOffset 13)
        (OptionMenu5.BottomOffset 13)
        (OptionMenu5.LeftOffset 3)
        (OptionMenu5.RightOffset 10)
        (.Label "Момент сил не известен")
        (.Layout
            (Grid
                (Rows 0)
                (Cols 0 1)
                Label16 OptionMenu5
            )
        )
    )
)
